# Generated by Django 6.0.1 on 2026-01-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_average_rating_book_reviews_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('History', 'History'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller')], max_length=50),
        ),
    ]
