# Generated by Django 6.0.2 on 2026-02-15 22:31

import django.core.validators
import travelers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[travelers.models.validate_email_domain])),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('country', models.CharField(choices=[('BG', 'Bulgaria'), ('UK', 'United Kingdom'), ('DE', 'Germany'), ('FR', 'France'), ('US', 'United States'), ('CA', 'Canada'), ('AU', 'Australia'), ('OTHER', 'Other')], default='OTHER', max_length=5)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-registered_at',),
            },
        ),
    ]
