# Generated by Django 6.0.2 on 2026-02-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='country',
            field=models.CharField(choices=[('BG', 'Bulgaria'), ('UK', 'United Kingdom'), ('DE', 'Germany'), ('FR', 'France'), ('SP', 'Spain'), ('IT', 'Italy'), ('US', 'United States'), ('CA', 'Canada'), ('AU', 'Australia'), ('OTHER', 'Other')], default='OTHER', max_length=5),
        ),
    ]
