# Generated by Django 6.0.1 on 2026-02-14 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('photos', '0002_alter_photo_tagged_pets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Comment',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_and_time_of_publication']},
        ),
    ]
